### ISSUE TITLE
command to cycle through action sets

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#43]
On the atom plugin, the ability I added to type out the name of action set, feels too slow. Instead I would like to switch action sets with a single command. I only have had two action sets thus far and having a command to cycle through the action sets would be awesome. Then I could easily switch to other action sets without having to worry / remember the name / index.

**Comment by dmh43** [comment]
How would the editor know what the current action set is? This seems like something more naturally implemented on the editor side.

**Comment by charlierudolph** [comment]
The editor just tells tertestrial to move to the next action set. Tertestrial will output what the new action set it

**Comment by dmh43** [comment]
@charlierudolph, I might be missing something, but as far as I know, Tertestrial can't talk to the editor at this point, right? So if the editor just tells Tertestrial to go to the next action set, how will the user know which action set is currently active? 

I guess the plugin could keep track of how many times the "nextActionSet" command was called, but that seems flimsy to me since it could get out of sync with the actual state of Tertestrial (if an error occurred while setting the action set, for example).

**Comment by charlierudolph** [comment]
The tertestrial server outputs what the new action set. See the code [here](https://github.com/Originate/tertestrial-server/blob/master/src/command-runner.ls#L60)  The editor won't be able to report what the new action set is but the user will still be able to know.

**Comment by dmh43** [comment]
@charlierudolph ahh missed that! Seems easy enough to implement this in Tertestrial rather than have to implement it in each plugin 👍

**Comment by charlierudolph** [comment]
Just implemented this on the atom plugin and love it. Switching action sets is now so easy!

**Comment by kevgo** [comment]
🎈🎉 😃
