### ISSUE TITLE
Overriding a Debug Statement Without Killing Tertestrial

### ISSUE THREAD

**Issue by dhakiki** [Originate/tertestrial-server#56]
If I have a Debug statement when I'm implementing a test and I need to inspect something, once I'm done I'd like to exit the test without killing Tertestrial!

**Comment by charlierudolph** [comment]
@dhakiki is this covered in #55? We also already kill the current running test if you start a new one. Otherwise what interface are your thinking? 

Also should we consider the ability to interact with the debugger? Maybe if running tertestrial in the foreground, we could forward stdin to that of the current running test (if one exists)

**Comment by dhakiki** [comment]
Yea, I guess that would be the same!

**Comment by dhakiki** [comment]
Closing as this issue is covered in #55.
